// build-index.js
// Vercel runs this on every deploy (see "buildCommand" in vercel.json).
// It scans  samples/<category>/<name>/index.html  and rewrites samples-data.js,
// so you never have to edit samples-data.js by hand again.
//
// What it does
//   - New folder with an index.html  -> chip is added automatically
//   - Folder deleted                  -> its chip is removed automatically
//   - Existing entries keep their name / template flag / order (taken from samples-data.js)
//
// Rules for NEW folders
//   - Category  = the folder directly under samples/   (gym, salon, dental ...)
//   - Name      = folder name made pretty              (iron-fitness -> "Iron Fitness")
//   - Template  = true only if the folder name starts with "template-"
//                 (template-dark-bold -> "Gym · Dark Bold"); everything else is
//                 treated as a real business name, so it stays hidden in "Templates only".
//   - Optional  samples/<category>/<name>/sample.json   {"name":"My Gym","template":true}
//                 overrides the name / template flag for that sample.

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const ROOT = __dirname;
const SAMPLES_DIR = path.join(ROOT, 'samples');
const DATA_FILE = path.join(ROOT, 'samples-data.js');

const pretty = (s) =>
  s.replace(/^\d+[-_]/, '').replace(/^template[-_]/, '')
   .split(/[-_\s]+/).filter(Boolean)
   .map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');

const subdirs = (dir) =>
  fs.existsSync(dir)
    ? fs.readdirSync(dir, { withFileTypes: true })
        .filter((d) => d.isDirectory() && !d.name.startsWith('.'))
        .map((d) => d.name).sort()
    : [];

// ---- 1. read what is already in samples-data.js
let cats = [], samples = [];
try {
  const sandbox = { window: {} };
  vm.runInNewContext(fs.readFileSync(DATA_FILE, 'utf8'), sandbox);
  cats = sandbox.window.CATEGORIES || [];
  samples = sandbox.window.SAMPLES || [];
} catch (e) {
  console.log('[build-index] no readable samples-data.js, starting fresh');
}

// ---- 2. scan the folders
const found = new Map(); // "cat/slug" -> { cat, slug, override }
for (const cat of subdirs(SAMPLES_DIR)) {
  const catDir = path.join(SAMPLES_DIR, cat);
  if (fs.existsSync(path.join(catDir, 'index.html'))) {
    console.log(`[build-index] WARNING: samples/${cat}/index.html sits directly in the category folder - ` +
                `move it to samples/${cat}/<name>/index.html`);
  }
  for (const slug of subdirs(catDir)) {
    const dir = path.join(catDir, slug);
    if (!fs.existsSync(path.join(dir, 'index.html'))) continue;
    let override = {};
    try { override = JSON.parse(fs.readFileSync(path.join(dir, 'sample.json'), 'utf8')); } catch (e) {}
    found.set(`${cat}/${slug}`, { cat, slug, override });
  }
}

// ---- 3. merge: keep existing (minus deleted folders), then append new ones
const log = [];
const kept = [];
for (const s of samples) {
  const f = found.get(s.path);
  if (!f) { log.push(`- removed  ${s.path}`); continue; }
  const next = { ...s };
  if (typeof f.override.name === 'string') next.name = f.override.name;
  if (typeof f.override.template === 'boolean') next.template = f.override.template;
  kept.push(next);
}
const have = new Set(kept.map((s) => s.path));
for (const [p, f] of found) {
  if (have.has(p)) continue;
  const isTpl = /^template[-_]/.test(f.slug);
  const name = typeof f.override.name === 'string' ? f.override.name
             : isTpl ? `${pretty(f.cat)} · ${pretty(f.slug)}` : pretty(f.slug);
  const template = typeof f.override.template === 'boolean' ? f.override.template : isTpl;
  kept.push({ name, cat: f.cat, template, path: p });
  log.push(`+ added    ${p}  ->  "${name}"  (${template ? 'template' : 'real name'})`);
}

// categories: keep existing order, new ones go just before "other"
const catIds = new Set(cats.map((c) => c.id));
for (const s of kept) {
  if (catIds.has(s.cat)) continue;
  const entry = { id: s.cat, label: pretty(s.cat) };
  const otherAt = cats.findIndex((c) => c.id === 'other');
  if (otherAt === -1) cats.push(entry); else cats.splice(otherAt, 0, entry);
  catIds.add(s.cat);
  log.push(`+ category ${s.cat}  ->  "${entry.label}"`);
}

// ---- 4. write samples-data.js
const out =
  '// AUTO-GENERATED by build-index.js on every deploy - you do not need to edit this file.\n' +
  '// Edit a name / category label here if you want; it is kept. Folder deleted = chip removed.\n' +
  '// template:true = placeholder name (safe to show anyone)   template:false = real business name\n' +
  'window.CATEGORIES = ' + JSON.stringify(cats) + ';\n' +
  'window.SAMPLES = [\n' + kept.map((s) => '  ' + JSON.stringify(s) + ',').join('\n') + '\n];\n';

fs.writeFileSync(DATA_FILE, out);
console.log(`[build-index] ${kept.length} samples` + (log.length ? '\n' + log.join('\n') : ' (no changes)'));
