// Add a new sample: copy its folder to samples/<category>/<slug>/ and add ONE line below.
// template:true  = placeholder name (safe to show anyone)   template:false = real business name
window.CATEGORIES = [{"id": "jewellery", "label": "Jewellery"}, {"id": "dental", "label": "Dental"}, {"id": "real-estate", "label": "Real Estate"}, {"id": "food-cafe", "label": "Food & Cafe"}, {"id": "hotels", "label": "Hotels"}, {"id": "healthcare", "label": "Healthcare"}, {"id": "education", "label": "Education"}, {"id": "gym", "label": "Gym & Fitness"},{"id": "other", "label": "Other"}];
window.SAMPLES = [
  {"name": "Fine Jewellery · Cream & Gold", "cat": "jewellery", "template": true, "path": "jewellery/template-cream-gold"},
  {"name": "Ghasi Ram Jewellers", "cat": "jewellery", "template": false, "path": "jewellery/ghasi-ram-jewellers"},
  {"name": "Premsons Jewellers", "cat": "jewellery", "template": false, "path": "jewellery/premsons-jewellers"},
  {"name": "Shri Ram Jewellers", "cat": "jewellery", "template": false, "path": "jewellery/shri-ram-jewellers"},
  {"name": "Radha Jewellers", "cat": "jewellery", "template": false, "path": "jewellery/radha-jewellers"},
  {"name": "Vriddhi by Sehgal", "cat": "jewellery", "template": false, "path": "jewellery/vriddhi-by-sehgal"},
  {"name": "Dental · Teal Clean", "cat": "dental", "template": true, "path": "dental/template-teal-clean"},
  {"name": "Dental · Warm Family", "cat": "dental", "template": true, "path": "dental/template-warm-family"},
  {"name": "Dental · Blue Specialist", "cat": "dental", "template": true, "path": "dental/template-blue-specialist"},
  {"name": "Dental · Sage Calm", "cat": "dental", "template": true, "path": "dental/template-sage-calm"},
  {"name": "Shaista Dental Clinic", "cat": "dental", "template": false, "path": "dental/shaista-dental-clinic"},
  {"name": "Shaista Dental Clinic · Design 2", "cat": "dental", "template": false, "path": "dental/shaista-dental-clinic-design-2"},
  {"name": "Ramaya Dentals", "cat": "dental", "template": false, "path": "dental/ramaya-dentals"},
  {"name": "Dental Studio Panipat", "cat": "dental", "template": false, "path": "dental/dental-studio-panipat"},
  {"name": "Dr Singla's Dental Clinic", "cat": "dental", "template": false, "path": "dental/dr-singla-dental-clinic"},
  {"name": "Real Estate · Cream & Gold", "cat": "real-estate", "template": true, "path": "real-estate/template-cream-gold"},
  {"name": "Real Estate · Dark Luxury", "cat": "real-estate", "template": true, "path": "real-estate/template-dark-luxury"},
  {"name": "Real Estate · Green Modern", "cat": "real-estate", "template": true, "path": "real-estate/template-green-modern"},
  {"name": "Cafe · Bright Yellow", "cat": "food-cafe", "template": true, "path": "food-cafe/template-bright-yellow"},
  {"name": "Cafe · Night Plum", "cat": "food-cafe", "template": true, "path": "food-cafe/template-night-plum"},
  {"name": "Cafe · Cream Brunch", "cat": "food-cafe", "template": true, "path": "food-cafe/template-cream-brunch"},
  {"name": "Qaenat Rooftop Restaurant", "cat": "food-cafe", "template": false, "path": "food-cafe/qaenat-rooftop-restaurant"},
  {"name": "Crazy Foods", "cat": "food-cafe", "template": false, "path": "food-cafe/crazy-foods-kharkhoda"},
  {"name": "Cafe Ocean Blue", "cat": "food-cafe", "template": false, "path": "food-cafe/cafe-ocean-blue"},
  {"name": "The Catalina Hotel & Banquets", "cat": "hotels", "template": false, "path": "hotels/catalina-hotel-banquets"},
  {"name": "Hotel L'Avenir", "cat": "hotels", "template": false, "path": "hotels/hotel-lavenir"},
  {"name": "Hotel Landlord Premier", "cat": "hotels", "template": false, "path": "hotels/hotel-landlord-premier"},
  {"name": "Oxygen Hospital", "cat": "healthcare", "template": false, "path": "healthcare/oxygen-hospital"},
  {"name": "Sanjivani Chiropractic", "cat": "healthcare", "template": false, "path": "healthcare/sanjivani-chiropractic"},
  {"name": "S.D. Memorial Convent School", "cat": "education", "template": false, "path": "education/sd-memorial-convent-school"},
  {"name": "Narayan Manav Chetna Classes", "cat": "education", "template": false, "path": "education/narayan-manav-chetna-classes"},
  {"name": "AJ Fashion", "cat": "other", "template": false, "path": "other/aj-fashion"},
  {"name": "BTN Overseas", "cat": "other", "template": false, "path": "other/btn-overseas"},
  {"name": "Rudransh Modular Kitchens", "cat": "other", "template": false, "path": "other/rudransh-modular-kitchens"},
  {"name": "Gym · Dark Bold", "cat": "gym", "template": true, "path": "gym/template-dark-bold"},
];
